### ISSUE TITLE
Idea: selector based dark mode support

### ISSUE THREAD

**Issue by stereobooster** [remcohaszing/rehype-mermaid#16]
Hey 👋 . It's me again. I know I proposed previous version of dark mode https://github.com/remcohaszing/rehype-mermaid/issues/6. But here is one more twist to it.

In case of [selector based dark mode](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) (so people can select in the dropdown: dark, light, auto) picture doesn't work. See https://github.com/withastro/starlight/discussions/1829

Maybe we can add option for selector based dark mode. Generated HTML can look like this:

```html
<img id="mermaid-dark-0" class="mermaid-dark" … />
<img id="mermaid-0" class="mermaid-light" … />
```

And CSS for it can look like this:

```css
html[data-theme="light"] .mermaid-dark {
  display: none;
}

html[data-theme="dark"] .mermaid-light {
  display: none;
}
```

I know this may be too specific request. Up to your consideration
